// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry;

import com.azure.containers.containerregistry.implementation.V2SupportsImpl;
import com.azure.containers.containerregistry.implementation.models.AcrErrorsException;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.rest.Response;
import reactor.core.publisher.Mono;

/** Initializes a new instance of the asynchronous AzureContainerRegistry type. */
@ServiceClient(builder = AzureContainerRegistryBuilder.class, isAsync = true)
public final class V2SupportAsyncClient {
    private final V2SupportsImpl serviceClient;

    /**
     * Initializes an instance of V2Supports client.
     *
     * @param serviceClient the service client implementation.
     */
    V2SupportAsyncClient(V2SupportsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Tells whether this Docker Registry instance supports Docker Registry HTTP API v2.
     *
     * @throws AcrErrorsException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the completion.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> checkWithResponse() {
        return this.serviceClient.checkWithResponseAsync();
    }

    /**
     * Tells whether this Docker Registry instance supports Docker Registry HTTP API v2.
     *
     * @throws AcrErrorsException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the completion.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Void> check() {
        return this.serviceClient.checkAsync();
    }
}
