// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation;

import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/** Initializes a new instance of the AzureContainerRegistry type. */
public final class AzureContainerRegistryImpl {
    /** Registry login URL. */
    private final String url;

    /**
     * Gets Registry login URL.
     *
     * @return the url value.
     */
    public String getUrl() {
        return this.url;
    }

    /** The HTTP pipeline to send requests through. */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     *
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /** The serializer to serialize an object into a string. */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     *
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /** The V2SupportsImpl object to access its operations. */
    private final V2SupportsImpl v2Supports;

    /**
     * Gets the V2SupportsImpl object to access its operations.
     *
     * @return the V2SupportsImpl object.
     */
    public V2SupportsImpl getV2Supports() {
        return this.v2Supports;
    }

    /** The ManifestsImpl object to access its operations. */
    private final ManifestsImpl manifests;

    /**
     * Gets the ManifestsImpl object to access its operations.
     *
     * @return the ManifestsImpl object.
     */
    public ManifestsImpl getManifests() {
        return this.manifests;
    }

    /** The BlobsImpl object to access its operations. */
    private final BlobsImpl blobs;

    /**
     * Gets the BlobsImpl object to access its operations.
     *
     * @return the BlobsImpl object.
     */
    public BlobsImpl getBlobs() {
        return this.blobs;
    }

    /** The RepositoriesOperationsImpl object to access its operations. */
    private final RepositoriesOperationsImpl repositoriesOperations;

    /**
     * Gets the RepositoriesOperationsImpl object to access its operations.
     *
     * @return the RepositoriesOperationsImpl object.
     */
    public RepositoriesOperationsImpl getRepositoriesOperations() {
        return this.repositoriesOperations;
    }

    /** The TagsImpl object to access its operations. */
    private final TagsImpl tags;

    /**
     * Gets the TagsImpl object to access its operations.
     *
     * @return the TagsImpl object.
     */
    public TagsImpl getTags() {
        return this.tags;
    }

    /** The RefreshTokensImpl object to access its operations. */
    private final RefreshTokensImpl refreshTokens;

    /**
     * Gets the RefreshTokensImpl object to access its operations.
     *
     * @return the RefreshTokensImpl object.
     */
    public RefreshTokensImpl getRefreshTokens() {
        return this.refreshTokens;
    }

    /** The AccessTokensImpl object to access its operations. */
    private final AccessTokensImpl accessTokens;

    /**
     * Gets the AccessTokensImpl object to access its operations.
     *
     * @return the AccessTokensImpl object.
     */
    public AccessTokensImpl getAccessTokens() {
        return this.accessTokens;
    }

    /**
     * Initializes an instance of AzureContainerRegistry client.
     *
     * @param url Registry login URL.
     */
    AzureContainerRegistryImpl(String url) {
        this(
                new HttpPipelineBuilder()
                        .policies(new UserAgentPolicy(), new RetryPolicy(), new CookiePolicy())
                        .build(),
                JacksonAdapter.createDefaultSerializerAdapter(),
                url);
    }

    /**
     * Initializes an instance of AzureContainerRegistry client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param url Registry login URL.
     */
    AzureContainerRegistryImpl(HttpPipeline httpPipeline, String url) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), url);
    }

    /**
     * Initializes an instance of AzureContainerRegistry client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param url Registry login URL.
     */
    AzureContainerRegistryImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter, String url) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.url = url;
        this.v2Supports = new V2SupportsImpl(this);
        this.manifests = new ManifestsImpl(this);
        this.blobs = new BlobsImpl(this);
        this.repositoriesOperations = new RepositoriesOperationsImpl(this);
        this.tags = new TagsImpl(this);
        this.refreshTokens = new RefreshTokensImpl(this);
        this.accessTokens = new AccessTokensImpl(this);
    }
}
