// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.ArrayList;
import java.util.List;

/** List of manifest attributes. */
@JacksonXmlRootElement(localName = "ManifestAttributesManifest")
@Fluent
public final class ManifestAttributesManifest {
    /*
     * List of manifest attributes details
     */
    @JsonProperty("ManifestAttributesManifestReferences")
    private List<ManifestAttributesManifestReferences> references = new ArrayList<>();

    /*
     * Quarantine tag name
     */
    @JsonProperty(value = "quarantineTag")
    private String quarantineTag;

    /**
     * Get the references property: List of manifest attributes details.
     *
     * @return the references value.
     */
    public List<ManifestAttributesManifestReferences> getReferences() {
        return this.references;
    }

    /**
     * Set the references property: List of manifest attributes details.
     *
     * @param references the references value to set.
     * @return the ManifestAttributesManifest object itself.
     */
    public ManifestAttributesManifest setReferences(List<ManifestAttributesManifestReferences> references) {
        this.references = references;
        return this;
    }

    /**
     * Get the quarantineTag property: Quarantine tag name.
     *
     * @return the quarantineTag value.
     */
    public String getQuarantineTag() {
        return this.quarantineTag;
    }

    /**
     * Set the quarantineTag property: Quarantine tag name.
     *
     * @param quarantineTag the quarantineTag value to set.
     * @return the ManifestAttributesManifest object itself.
     */
    public ManifestAttributesManifest setQuarantineTag(String quarantineTag) {
        this.quarantineTag = quarantineTag;
        return this;
    }
}
