// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpRequest;
import com.azure.core.http.rest.ResponseBase;

/** Contains all response data for the getList operation. */
public final class RepositoriesGetListResponse extends ResponseBase<RepositoriesGetListHeaders, Repositories> {
    /**
     * Creates an instance of RepositoriesGetListResponse.
     *
     * @param request the request which resulted in this RepositoriesGetListResponse.
     * @param statusCode the status code of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param value the deserialized value of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     */
    public RepositoriesGetListResponse(
            HttpRequest request,
            int statusCode,
            HttpHeaders rawHeaders,
            Repositories value,
            RepositoriesGetListHeaders headers) {
        super(request, statusCode, rawHeaders, value, headers);
    }

    /** @return the deserialized response body. */
    @Override
    public Repositories getValue() {
        return super.getValue();
    }
}
