// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/** Tag attributes. */
@JacksonXmlRootElement(localName = "TagAttributes")
@Fluent
public final class TagAttributes {
    /*
     * Registry name
     */
    @JsonProperty(value = "registry")
    private String registry;

    /*
     * Image name
     */
    @JsonProperty(value = "imageName")
    private String imageName;

    /*
     * List of tag attribute details
     */
    @JsonProperty(value = "tag")
    private TagAttributesBase attributes;

    /**
     * Get the registry property: Registry name.
     *
     * @return the registry value.
     */
    public String getRegistry() {
        return this.registry;
    }

    /**
     * Set the registry property: Registry name.
     *
     * @param registry the registry value to set.
     * @return the TagAttributes object itself.
     */
    public TagAttributes setRegistry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * Get the imageName property: Image name.
     *
     * @return the imageName value.
     */
    public String getImageName() {
        return this.imageName;
    }

    /**
     * Set the imageName property: Image name.
     *
     * @param imageName the imageName value to set.
     * @return the TagAttributes object itself.
     */
    public TagAttributes setImageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * Get the attributes property: List of tag attribute details.
     *
     * @return the attributes value.
     */
    public TagAttributesBase getAttributes() {
        return this.attributes;
    }

    /**
     * Set the attributes property: List of tag attribute details.
     *
     * @param attributes the attributes value to set.
     * @return the TagAttributes object itself.
     */
    public TagAttributes setAttributes(TagAttributesBase attributes) {
        this.attributes = attributes;
        return this;
    }
}
