trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: containerregistry
      Artifacts:
        - name: azure-containers-containerregistry
          groupId: com.azure
          safeName: azurecontainerscontainerregistry
      EnvVars:
        AZURE_TEST_MODE: RECORD
