// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Manifest attributes. */
@Fluent
public final class AcrManifests {
    /*
     * Registry name
     */
    @JsonProperty(value = "registry")
    private String registry;

    /*
     * Image name
     */
    @JsonProperty(value = "imageName")
    private String imageName;

    /*
     * List of manifests
     */
    @JsonProperty(value = "manifests")
    private List<ManifestAttributesBase> manifestsAttributes;

    /**
     * Get the registry property: Registry name.
     *
     * @return the registry value.
     */
    public String getRegistry() {
        return this.registry;
    }

    /**
     * Set the registry property: Registry name.
     *
     * @param registry the registry value to set.
     * @return the AcrManifests object itself.
     */
    public AcrManifests setRegistry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * Get the imageName property: Image name.
     *
     * @return the imageName value.
     */
    public String getImageName() {
        return this.imageName;
    }

    /**
     * Set the imageName property: Image name.
     *
     * @param imageName the imageName value to set.
     * @return the AcrManifests object itself.
     */
    public AcrManifests setImageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * Get the manifestsAttributes property: List of manifests.
     *
     * @return the manifestsAttributes value.
     */
    public List<ManifestAttributesBase> getManifestsAttributes() {
        return this.manifestsAttributes;
    }

    /**
     * Set the manifestsAttributes property: List of manifests.
     *
     * @param manifestsAttributes the manifestsAttributes value to set.
     * @return the AcrManifests object itself.
     */
    public AcrManifests setManifestsAttributes(List<ManifestAttributesBase> manifestsAttributes) {
        this.manifestsAttributes = manifestsAttributes;
        return this;
    }
}
