// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.ArrayList;
import java.util.List;

/** Deleted repository. */
@JacksonXmlRootElement(localName = "DeletedRepository")
@Fluent
public final class DeletedRepository {
    /*
     * SHA of the deleted image
     */
    @JsonProperty("DeletedRepositoryManifestsDeletedItem")
    private List<String> manifestsDeleted = new ArrayList<>();

    /*
     * Tag of the deleted image
     */
    @JsonProperty("DeletedRepositoryTagsDeletedItem")
    private List<String> tagsDeleted = new ArrayList<>();

    /**
     * Get the manifestsDeleted property: SHA of the deleted image.
     *
     * @return the manifestsDeleted value.
     */
    public List<String> getManifestsDeleted() {
        return this.manifestsDeleted;
    }

    /**
     * Set the manifestsDeleted property: SHA of the deleted image.
     *
     * @param manifestsDeleted the manifestsDeleted value to set.
     * @return the DeletedRepository object itself.
     */
    public DeletedRepository setManifestsDeleted(List<String> manifestsDeleted) {
        this.manifestsDeleted = manifestsDeleted;
        return this;
    }

    /**
     * Get the tagsDeleted property: Tag of the deleted image.
     *
     * @return the tagsDeleted value.
     */
    public List<String> getTagsDeleted() {
        return this.tagsDeleted;
    }

    /**
     * Set the tagsDeleted property: Tag of the deleted image.
     *
     * @param tagsDeleted the tagsDeleted value to set.
     * @return the DeletedRepository object itself.
     */
    public DeletedRepository setTagsDeleted(List<String> tagsDeleted) {
        this.tagsDeleted = tagsDeleted;
        return this;
    }
}
