// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/** Manifest attributes details. */
@JacksonXmlRootElement(localName = "ManifestAttributes")
@Fluent
public final class ManifestAttributes {
    /*
     * Registry name
     */
    @JsonProperty(value = "registry")
    private String registry;

    /*
     * Image name
     */
    @JsonProperty(value = "imageName")
    private String imageName;

    /*
     * Manifest attributes
     */
    @JsonProperty(value = "manifest")
    private ManifestAttributesBase attributes;

    /**
     * Get the registry property: Registry name.
     *
     * @return the registry value.
     */
    public String getRegistry() {
        return this.registry;
    }

    /**
     * Set the registry property: Registry name.
     *
     * @param registry the registry value to set.
     * @return the ManifestAttributes object itself.
     */
    public ManifestAttributes setRegistry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * Get the imageName property: Image name.
     *
     * @return the imageName value.
     */
    public String getImageName() {
        return this.imageName;
    }

    /**
     * Set the imageName property: Image name.
     *
     * @param imageName the imageName value to set.
     * @return the ManifestAttributes object itself.
     */
    public ManifestAttributes setImageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * Get the attributes property: Manifest attributes.
     *
     * @return the attributes value.
     */
    public ManifestAttributesBase getAttributes() {
        return this.attributes;
    }

    /**
     * Set the attributes property: Manifest attributes.
     *
     * @param attributes the attributes value to set.
     * @return the ManifestAttributes object itself.
     */
    public ManifestAttributes setAttributes(ManifestAttributesBase attributes) {
        this.attributes = attributes;
        return this;
    }
}
