// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Manifest details. */
@Fluent
public final class ManifestAttributesBase {
    /*
     * Manifest
     */
    @JsonProperty(value = "digest")
    private String digest;

    /*
     * Image size
     */
    @JsonProperty(value = "imageSize")
    private Long imageSize;

    /*
     * Created time
     */
    @JsonProperty(value = "createdTime")
    private String createdTime;

    /*
     * Last update time
     */
    @JsonProperty(value = "lastUpdateTime")
    private String lastUpdateTime;

    /*
     * CPU architecture
     */
    @JsonProperty(value = "architecture")
    private String architecture;

    /*
     * Operating system
     */
    @JsonProperty(value = "os")
    private String os;

    /*
     * Media type
     */
    @JsonProperty(value = "mediaType")
    private String mediaType;

    /*
     * Config blob media type
     */
    @JsonProperty(value = "configMediaType")
    private String configMediaType;

    /*
     * List of tags
     */
    @JsonProperty(value = "tags")
    private List<String> tags;

    /*
     * Changeable attributes
     */
    @JsonProperty(value = "changeableAttributes")
    private ChangeableAttributes changeableAttributes;

    /**
     * Get the digest property: Manifest.
     *
     * @return the digest value.
     */
    public String getDigest() {
        return this.digest;
    }

    /**
     * Set the digest property: Manifest.
     *
     * @param digest the digest value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setDigest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * Get the imageSize property: Image size.
     *
     * @return the imageSize value.
     */
    public Long getImageSize() {
        return this.imageSize;
    }

    /**
     * Set the imageSize property: Image size.
     *
     * @param imageSize the imageSize value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setImageSize(Long imageSize) {
        this.imageSize = imageSize;
        return this;
    }

    /**
     * Get the createdTime property: Created time.
     *
     * @return the createdTime value.
     */
    public String getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Set the createdTime property: Created time.
     *
     * @param createdTime the createdTime value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Get the lastUpdateTime property: Last update time.
     *
     * @return the lastUpdateTime value.
     */
    public String getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    /**
     * Set the lastUpdateTime property: Last update time.
     *
     * @param lastUpdateTime the lastUpdateTime value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    /**
     * Get the architecture property: CPU architecture.
     *
     * @return the architecture value.
     */
    public String getArchitecture() {
        return this.architecture;
    }

    /**
     * Set the architecture property: CPU architecture.
     *
     * @param architecture the architecture value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setArchitecture(String architecture) {
        this.architecture = architecture;
        return this;
    }

    /**
     * Get the os property: Operating system.
     *
     * @return the os value.
     */
    public String getOs() {
        return this.os;
    }

    /**
     * Set the os property: Operating system.
     *
     * @param os the os value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setOs(String os) {
        this.os = os;
        return this;
    }

    /**
     * Get the mediaType property: Media type.
     *
     * @return the mediaType value.
     */
    public String getMediaType() {
        return this.mediaType;
    }

    /**
     * Set the mediaType property: Media type.
     *
     * @param mediaType the mediaType value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setMediaType(String mediaType) {
        this.mediaType = mediaType;
        return this;
    }

    /**
     * Get the configMediaType property: Config blob media type.
     *
     * @return the configMediaType value.
     */
    public String getConfigMediaType() {
        return this.configMediaType;
    }

    /**
     * Set the configMediaType property: Config blob media type.
     *
     * @param configMediaType the configMediaType value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setConfigMediaType(String configMediaType) {
        this.configMediaType = configMediaType;
        return this;
    }

    /**
     * Get the tags property: List of tags.
     *
     * @return the tags value.
     */
    public List<String> getTags() {
        return this.tags;
    }

    /**
     * Set the tags property: List of tags.
     *
     * @param tags the tags value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setTags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the changeableAttributes property: Changeable attributes.
     *
     * @return the changeableAttributes value.
     */
    public ChangeableAttributes getChangeableAttributes() {
        return this.changeableAttributes;
    }

    /**
     * Set the changeableAttributes property: Changeable attributes.
     *
     * @param changeableAttributes the changeableAttributes value to set.
     * @return the ManifestAttributesBase object itself.
     */
    public ManifestAttributesBase setChangeableAttributes(ChangeableAttributes changeableAttributes) {
        this.changeableAttributes = changeableAttributes;
        return this;
    }
}
