// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.ArrayList;
import java.util.List;

/** List of repositories. */
@JacksonXmlRootElement(localName = "Repositories")
@Fluent
public final class Repositories {
    /*
     * Repository names
     */
    @JsonProperty("RepositoriesItem")
    private List<String> names = new ArrayList<>();

    /**
     * Get the names property: Repository names.
     *
     * @return the names value.
     */
    public List<String> getNames() {
        return this.names;
    }

    /**
     * Set the names property: Repository names.
     *
     * @param names the names value to set.
     * @return the Repositories object itself.
     */
    public Repositories setNames(List<String> names) {
        this.names = names;
        return this;
    }
}
