// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Repository attributes. */
@Fluent
public final class RepositoryAttributes {
    /*
     * Registry name
     */
    @JsonProperty(value = "registry")
    private String registry;

    /*
     * Image name
     */
    @JsonProperty(value = "imageName")
    private String imageName;

    /*
     * Image created time
     */
    @JsonProperty(value = "createdTime")
    private String createdTime;

    /*
     * Image last update time
     */
    @JsonProperty(value = "lastUpdateTime")
    private String lastUpdateTime;

    /*
     * Number of the manifests
     */
    @JsonProperty(value = "manifestCount")
    private Integer manifestCount;

    /*
     * Number of the tags
     */
    @JsonProperty(value = "tagCount")
    private Integer tagCount;

    /*
     * Changeable attributes
     */
    @JsonProperty(value = "changeableAttributes")
    private ChangeableAttributes changeableAttributes;

    /**
     * Get the registry property: Registry name.
     *
     * @return the registry value.
     */
    public String getRegistry() {
        return this.registry;
    }

    /**
     * Set the registry property: Registry name.
     *
     * @param registry the registry value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setRegistry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * Get the imageName property: Image name.
     *
     * @return the imageName value.
     */
    public String getImageName() {
        return this.imageName;
    }

    /**
     * Set the imageName property: Image name.
     *
     * @param imageName the imageName value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setImageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * Get the createdTime property: Image created time.
     *
     * @return the createdTime value.
     */
    public String getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Set the createdTime property: Image created time.
     *
     * @param createdTime the createdTime value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Get the lastUpdateTime property: Image last update time.
     *
     * @return the lastUpdateTime value.
     */
    public String getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    /**
     * Set the lastUpdateTime property: Image last update time.
     *
     * @param lastUpdateTime the lastUpdateTime value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    /**
     * Get the manifestCount property: Number of the manifests.
     *
     * @return the manifestCount value.
     */
    public Integer getManifestCount() {
        return this.manifestCount;
    }

    /**
     * Set the manifestCount property: Number of the manifests.
     *
     * @param manifestCount the manifestCount value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setManifestCount(Integer manifestCount) {
        this.manifestCount = manifestCount;
        return this;
    }

    /**
     * Get the tagCount property: Number of the tags.
     *
     * @return the tagCount value.
     */
    public Integer getTagCount() {
        return this.tagCount;
    }

    /**
     * Set the tagCount property: Number of the tags.
     *
     * @param tagCount the tagCount value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setTagCount(Integer tagCount) {
        this.tagCount = tagCount;
        return this;
    }

    /**
     * Get the changeableAttributes property: Changeable attributes.
     *
     * @return the changeableAttributes value.
     */
    public ChangeableAttributes getChangeableAttributes() {
        return this.changeableAttributes;
    }

    /**
     * Set the changeableAttributes property: Changeable attributes.
     *
     * @param changeableAttributes the changeableAttributes value to set.
     * @return the RepositoryAttributes object itself.
     */
    public RepositoryAttributes setChangeableAttributes(ChangeableAttributes changeableAttributes) {
        this.changeableAttributes = changeableAttributes;
        return this;
    }
}
