// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/** Tag attribute details. */
@JacksonXmlRootElement(localName = "TagAttributesBase")
@Fluent
public final class TagAttributesBase {
    /*
     * Tag name
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * Tag digest
     */
    @JsonProperty(value = "digest")
    private String digest;

    /*
     * Tag created time
     */
    @JsonProperty(value = "createdTime")
    private String createdTime;

    /*
     * Tag last update time
     */
    @JsonProperty(value = "lastUpdateTime")
    private String lastUpdateTime;

    /*
     * Is signed
     */
    @JsonProperty(value = "signed")
    private Boolean signed;

    /*
     * Changeable attributes
     */
    @JsonProperty(value = "changeableAttributes")
    private ChangeableAttributes changeableAttributes;

    /**
     * Get the name property: Tag name.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Tag name.
     *
     * @param name the name value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the digest property: Tag digest.
     *
     * @return the digest value.
     */
    public String getDigest() {
        return this.digest;
    }

    /**
     * Set the digest property: Tag digest.
     *
     * @param digest the digest value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setDigest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * Get the createdTime property: Tag created time.
     *
     * @return the createdTime value.
     */
    public String getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Set the createdTime property: Tag created time.
     *
     * @param createdTime the createdTime value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Get the lastUpdateTime property: Tag last update time.
     *
     * @return the lastUpdateTime value.
     */
    public String getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    /**
     * Set the lastUpdateTime property: Tag last update time.
     *
     * @param lastUpdateTime the lastUpdateTime value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    /**
     * Get the signed property: Is signed.
     *
     * @return the signed value.
     */
    public Boolean isSigned() {
        return this.signed;
    }

    /**
     * Set the signed property: Is signed.
     *
     * @param signed the signed value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setSigned(Boolean signed) {
        this.signed = signed;
        return this;
    }

    /**
     * Get the changeableAttributes property: Changeable attributes.
     *
     * @return the changeableAttributes value.
     */
    public ChangeableAttributes getChangeableAttributes() {
        return this.changeableAttributes;
    }

    /**
     * Set the changeableAttributes property: Changeable attributes.
     *
     * @param changeableAttributes the changeableAttributes value to set.
     * @return the TagAttributesBase object itself.
     */
    public TagAttributesBase setChangeableAttributes(ChangeableAttributes changeableAttributes) {
        this.changeableAttributes = changeableAttributes;
        return this;
    }
}
