// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.containers.containerregistry.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** List of tag details. */
@Fluent
public final class TagList {
    /*
     * Registry name
     */
    @JsonProperty(value = "registry")
    private String registry;

    /*
     * Image name
     */
    @JsonProperty(value = "imageName")
    private String imageName;

    /*
     * List of tag attribute details
     */
    @JsonProperty(value = "tags")
    private List<TagAttributesBase> tags;

    /**
     * Get the registry property: Registry name.
     *
     * @return the registry value.
     */
    public String getRegistry() {
        return this.registry;
    }

    /**
     * Set the registry property: Registry name.
     *
     * @param registry the registry value to set.
     * @return the TagList object itself.
     */
    public TagList setRegistry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * Get the imageName property: Image name.
     *
     * @return the imageName value.
     */
    public String getImageName() {
        return this.imageName;
    }

    /**
     * Set the imageName property: Image name.
     *
     * @param imageName the imageName value to set.
     * @return the TagList object itself.
     */
    public TagList setImageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * Get the tags property: List of tag attribute details.
     *
     * @return the tags value.
     */
    public List<TagAttributesBase> getTags() {
        return this.tags;
    }

    /**
     * Set the tags property: List of tag attribute details.
     *
     * @param tags the tags value to set.
     * @return the TagList object itself.
     */
    public TagList setTags(List<TagAttributesBase> tags) {
        this.tags = tags;
        return this;
    }
}
